
[package]
name = "blesschain-runtime"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
frame-support = { path = "../../blesschain-sdk/frame/support", default-features = false }
frame-system = { path = "../../blesschain-sdk/frame/system", default-features = false }
pallet-balances = { path = "../../blesschain-sdk/frame/balances", default-features = false }
pallet-timestamp = { path = "../../blesschain-sdk/frame/timestamp", default-features = false }
pallet-aura = { path = "../../blesschain-sdk/frame/aura", default-features = false }
sp-runtime = { path = "../../blesschain-sdk/primitives/runtime", default-features = false }
sp-api = { path = "../../blesschain-sdk/primitives/api", default-features = false }
sp-consensus-aura = { path = "../../blesschain-sdk/primitives/consensus/aura", default-features = false }
sp-core = { path = "../../blesschain-sdk/primitives/core", default-features = false }
sp-std = { path = "../../blesschain-sdk/primitives/std", default-features = false }
sp-inherents = { path = "../../blesschain-sdk/primitives/inherents", default-features = false }
sp-version = { path = "../../blesschain-sdk/primitives/version", default-features = false }

[features]
default = ["std"]
std = [
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    "pallet-timestamp/std",
    "pallet-aura/std",
    "sp-runtime/std",
    "sp-api/std",
    "sp-consensus-aura/std",
    "sp-core/std",
    "sp-std/std",
    "sp-inherents/std",
    "sp-version/std",
]
